### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by davidgranstrom** [davidgranstrom/scnvim#95]
Various small fixes for v1.0.0 that doesn't need separate issues.

- [x] Get current UDP port directly from lua module before recompile
- [x] Escape `scdoc_render_prg` path
- [x] Remove `autoload/scnvim/lua.vim`
- [x] Update README (move stuff to wiki, and add links)
- [x] Check/Add headers (documentation)
- [ ] Tag release

**Comment by dvzrv** [comment]
@davidgranstrom hey, thanks for rewriting this in lua. When will there be a release? I'd package it for Arch Linux! :)

**Comment by davidgranstrom** [comment]
@dvzrv Hi! Thank you for your interest in this project. I would be happy to create a release to help with packaging, but I would like to wait and get feedback on #210 before this since it involves a (minor) breaking change in the user configuration API.
